create database EMPLOYEE;
USE EMPLOYEE;
CREATE TABLE EMPLOYEE(ID INT,USERNAME VARCHAR(225),PASSWORD VARCHAR(225),FULLNAME VARCHAR(225),EMAIL VARCHAR(225), MOBILE_NUMBER BIGINT);
select * from employee;